export const categories = [
  "Electronics",
  "Men Clothing",
  "Woman Clothing",
  "Books",
  "Beauty and Personal Care",
  "Sports and Outdoors",
  "Home and Living",
  "Stationery and Office Supplies",
  "Jewelry and Accessories",
  "Health and Wellness",
  "Toys and Games",
  "Food and Beverages",
  "Art and Craft Supplies",
  "Automotive",
  "Fitness and Exercise",
  "Pet Supplies",
  "Garden and Outdoor",
  "Travel and Luggage",
  "Baby and Kids",
  "Party and Celebration",
  "Musical Instruments",
];
